---
framework: jest
tier: xlarge
postMerge:
  pattern:
    - "./tests/unit/chart/chart-spec.ts"
preMerge:
  pattern:
    - "./tests/unit/chart/chart-spec.ts"
preRun:
     command:
        - npm install
postRun:
     command:
        - node --version
version: 2.1
